    
theme: jekyll-theme-cayman
show_downloads: true
locale                   : "it"
title                    : "GaiaGo - P2PCS"
name                     : &name "FourteenRows"
url                      : https://fourteenrows.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/P2PCS" # the subpath of your site, e.g. "/blog"
repository               : "P2PCS"
staticman:
  branch                 : "gh-pages" # "master", "gh-pages"
author:
  name             : "FourteenRows"
